# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastKins' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
  # Pods for FastKins

  target 'FastKinsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FastKinsUITests' do
    # Pods for testing
  end

end
