# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastKins' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.0'
  # Pods for FastKins
  
  target 'FastKinsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 5.0'
  end
  
  target 'FastKinsUITests' do
    # Pods for testing
    pod 'Alamofire', '~> 5.0'
  end
  
end
